### ISSUE TITLE
Get the directory generation test working

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#159]
https://travis-ci.org/Caleydo/caleydo.github.io/builds/161920383#L416:
```
$ bash .build-tools/cron_job.sh
/home/travis/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:353:in `open_http': 403 Forbidden (OpenURI::HTTPError)
...
	from .build-tools/read_github.rb:10:in `block in repos_by_type'
```

(I hadn't noticed that I wasn't receiving notifications.)

In a way, this doesn't surprise me: I'm guessing github flagged us for hitting the API too hard.

- Just checked, and the top level repo list does return modification date... so we could only get the readmes for the ones that have changed: A lot faster, but a little more complicated?
- Since neither I nor anyone else noticed that this wasn't working, maybe the cron job idea doesn't work for us? Maybe just a tool that can be run by a human to update the list?

**Comment by mccalluc** [comment]
- Travis was still configured for cron runs: cleared that.
- I'm comfortable rerunning the script by hand: Simple, and it works.
